# Generated by Django 3.0.2 on 2020-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200609_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
